### ISSUE TITLE
question regarding The space cryptoanalysis 

### ISSUE THREAD

**Issue by yoavst** [CameronLonsdale/MTP#18]
Could you explain the space cryptoanalysis?
I've been thinking about it for a while and couldn't find a satisficing explanation.

What is the expected character set?

**Comment by CameronLonsdale** [comment]
It's essentially just a guess. We're assuming the text you're decrypting is English (or equivalent) sentences which would have a lot of spaces in it. So we try to find if there are spaces in the ciphertexts provided to decrypt.

Since it's XOR, we can learn something about the plain text by xor'ing ciphertexts together. Because it will be the plaintext letter XOR a plaintext letter. If you check out an ascii table, you'll see that if you XOR a space with a letter (or a space with a space) you'll get either 0x00, or another ascii letter. Which is what we do in this function:

```
def is_space(char: int) -> bool:
    """
    An XOR'ed character will be a space (or any punctuation character)
    if the resulting XOR of a ^ b is either 0x00, or an ascii letter
    """
    return char == 0x00 or chr(char) in string.ascii_letters
```

But it's still not guaranteed to be a space, its just a guess. But we can get more confident about our guess by keeping track of how many spaces we think we see in the same position, and if we see it many times, we are more confident we know what the plaintext letter was (a space), and therefore what part of the key was.

To learn more, I recommend checking out https://www.coursera.org/learn/crypto. Hopefully this helped you understand a bit more.
